repository:
  description: GitHub app that simplifies sharing configurations across repositories.

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: [ci, validate-pr]
