# last sha: b0ffea6d2f420e9ab022d00ae442a13106008ba8
_extends: .github

repository:
  description: Simplify sharing configurations across all your repositories.

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: [ci, validate-pr]
